### ISSUE TITLE
NSSet or NSOrderedSet properties

### ISSUE THREAD

**Issue by mojidabckuu** [CoderMJLee/MJExtension#193] opened 2015-09-06 11:24 UTC
Hi,
I am trying to convert from JSON to CoreData model.
I have relationship between 2 models `1 to many` and the property type of relation is `NSOrderedSet`. Is it possible to handle this situation and parse correctly?

**Comment by wolfcon** [comment] 2021-09-08 03:14
Duplicate of #43

**Closed by wolfcon** 2021-09-08 03:14 UTC
