### ISSUE TITLE
mj哥字典->coredata模型里面有个集合的话  失败了

### ISSUE THREAD

**Issue by feixue299** [CoderMJLee/MJExtension#296] opened 2015-12-15 07:00 UTC
服务器：
{
    errcode = 0;
    errmsg =     {
        RestTime =         (
                        {
                RestEndTime = "16:55:00";
                RestStartTime = "08:55:00";
            },
                        {
                RestEndTime = "21:30:00";
                RestStartTime = "08:00:00";
            }
        );
        WorkEndTime = "21:30:00";
        WorkStartTime = "08:00:00";
    };
}

@interface ClinicTime (CoreDataProperties)

@property (nullable, nonatomic, retain) NSString *workEndTime;
@property (nullable, nonatomic, retain) NSString *workStartTime;
@property (nullable, nonatomic, retain) NSSet<RestTime *> *restTime;

@end

转换之后打印的结果是这样的：
{
    restTime =     (
    );
    workEndTime = "21:30:00";
    workStartTime = "08:00:00";
}

我已经用了首字母大写了

**Comment by wolfcon** [comment] 2021-09-08 03:15
Duplicate of #43

**Closed by wolfcon** 2021-09-08 03:15 UTC
