### ISSUE TITLE
iOS13会出现闪退问题

### ISSUE THREAD

**Issue by stoneUoU** [CoderMJLee/MJExtension#719] opened 2019-08-21 03:20 UTC
#pragma mark - 公共方法
+ (NSMutableArray *)properties
{
    NSMutableArray *cachedProperties = [self propertyDictForKey:&MJCachedPropertiesKey][NSStringFromClass(self)];
    if (cachedProperties == nil) {
    
        if (cachedProperties == nil) {
            cachedProperties = [NSMutableArray array];
            
            [self mj_enumerateClasses:^(__unsafe_unretained Class c, BOOL *stop) {
                // 1.获得所有的成员变量
                unsigned int outCount = 0;
                objc_property_t *properties = class_copyPropertyList(c, &outCount);
                
                // 2.遍历每一个成员变量
                for (unsigned int i = 0; i<outCount; i++) {
                    MJProperty *property = [MJProperty cachedPropertyWithProperty:properties[i]];
                    // 过滤掉Foundation框架类里面的属性
                    if ([MJFoundation isClassFromFoundation:property.srcClass]) continue;
                    property.srcClass = c;
                    [property setOriginKey:[self propertyKey:property.name] forClass:self];
                    [property setObjectClassInArray:[self propertyObjectClassInArray:property.name] forClass:self];
                    [cachedProperties addObject:property];
                }
                
                // 3.释放内存
                free(properties);
            }];
            
            [self propertyDictForKey:&MJCachedPropertiesKey][NSStringFromClass(self)] = cachedProperties;
        }
    }
    
    return cachedProperties;
}

**Comment by stoneUoU** [comment] 2019-08-21 06:39
NSObject+MJProperty.m的153行
#pragma mark - 公共方法

(NSMutableArray *)properties
{
NSMutableArray *cachedProperties = [self dictForKey:&MJCachedPropertiesKey] [NSStringFromClass(self)];

**Comment by stoneUoU** [comment] 2019-08-21 07:03
[](url)

**Comment by stoneUoU** [comment] 2019-08-21 07:04
![Uploading AF64C1F9-C5B5-4041-9D43-F8D43A3E1A03.png…]()

**Comment by wolfcon** [comment] 2019-08-21 07:38
Demo?

**Comment by wolfcon** [comment] 2019-08-21 07:39
Duplicate of #713

**Closed by wolfcon** 2019-08-21 07:39 UTC
Labels: duplicate-重复的问题

**Comment by stoneUoU** [comment] 2019-08-21 08:50
怎么发demo给你？

**Comment by wolfcon** [comment] 2019-08-21 09:55
把 Demo 打成 zip 包 拖动到打字框里

**Comment by stoneUoU** [comment] 2019-09-18 07:19
我能私发给你吗？这是公司项目

**Comment by wolfcon** [comment] 2019-09-18 10:28
472730949@qq.com 发这个邮箱吧 / 加 QQ 也可以

**Comment by stoneUoU** [comment] 2019-09-19 03:20
嗯，好的
